name: Textile News Test

on:
  workflow_dispatch:

  schedule:
    - cron: '0 23 * * *'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: 输出测试信息
        run: |
          echo "====================="
          echo "纺织新闻自动任务启动"
          echo "当前时间："
          date
          echo "GitHub Actions 工作正常"
          echo "====================="
